name: blockchain
version: 0.1.0.0
github: 'githubuser/blockchain'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2019 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/blockchain#readme>

dependencies:
  - base >= 4.7 && < 5
  - protolude == 0.2.3
  - bytestring == 0.10.8.2
  - memory == 0.14.18
  - cryptonite == 0.25
  - free == 5.1.3
  - vector == 0.12.0.3
  - vector-binary-instances == 0.2.5.1
  - binary == 0.8.6.0

library:
  source-dirs: src

executables:
  blockchain-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blockchain

tests:
  blockchain-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blockchain
      - hspec
